# Site settings
title: Code for Münster
email: muenster@codefor.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "codeformuenster.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

collections:
  projekte:
      output: true
